Update README.md
do9core/gRPC-Demo pull request #1
Opened 2021-11-25 08:25 UTC by f-qiaolei

The package path has already contained in the .proto file, no need to switch path in the command line.

2021-11-29 14:51 UTC, do9core requested changes

2021-11-29 14:51 UTC, do9core commented on README.md
> +    protoc --go_out=plugins=grpc:. *.proto
Rather than change the command, maybe change the `go_package` in proto file would be better.

2021-11-30 01:20 UTC, f-qiaolei commented on README.md
> +    protoc --go_out=plugins=grpc:. *.proto
Updated, please check.

2021-11-30 12:27 UTC, do9core approved these changes

2021-11-30 12:27 UTC, do9core commented on README.md
> +    protoc --go_out=plugins=grpc:. *.proto
well done

2021-11-30 12:28 UTC, merged